### ISSUE TITLE
Offline session always is not valid

### ISSUE THREAD

**Issue by pomeo** [nestjs-shopify/nestjs-shopify#110]
Test:
`@UseShopifyAuth(AccessMode.Offline)`

https://github.com/nestjs-shopify/nestjs-shopify/blob/ea3d8e2315650767c04f666d56437364df012875/packages/auth/src/auth-session.service.ts#L20-L27

**Comment by tolgap** [comment]
@pomeo thanks for raising this issue! The fix is released as `@nestjs-shopify/auth@2.0.3` 🚀 .
