### ISSUE TITLE
Session token is null at endpoint

### ISSUE THREAD

**Issue by julkascript** [nestjs-shopify/nestjs-shopify#271]
Hello. We have configured nestjs-shopify/core and nestjs-shopify/auth for our Nest.js project. 
``` javascript
// app.module.ts
ShopifyAuthModule.forRootAsyncOffline({
  useFactory: () => ({
    useGlobalPrefix: true,
    basePath: 'shopify',
  }),
  inject: [],
}),

ShopifyCoreModule.forRoot({
  apiKey: process.env.SHOPIFY_APIKEY,
  apiSecretKey: process.env.SHOPIFY_APISECRETKEY,
  apiVersion: ApiVersion.Unstable,
  hostName: process.env.SHOPIFY_HOST,
  isEmbeddedApp: true,
  scopes: ['read_products'],
  sessionStorage: new PostgreSQLSessionStorage(process.env.POSTGRES_URL),
}),
```
We successfully store the access token of the shop in the Postgres database. When we try to get the `session` at our endpoint, it appears as `null`.

```javascript
// product.controller.ts
@UseShopifyAuth(AccessMode.Offline)
@Get('products/store')
async getStoreProducts(@CurrentSession() session: Session, @Req() req)   {
  console.log(session) // null
}
```
If we add an authHandler and try to console.log the `session` from the afterAuth function, we can see it.

**Could you give us some hints why we cannot retrieve the session from the endpoint, or could it be a bug?**

**Comment by tolgap** [comment]
@julkascript do you have any output in your NestJS process?

https://github.com/nestjs-shopify/nestjs-shopify/blob/main/packages/auth/src/auth.guard.ts#L80-L95

The `ShopifyAuthGuard` should perform logs when a session ID cannot be found.

**Comment by julkascript** [comment]
@tolgap The code that you quoted throws no errors, which means a session is loaded but then it returns `null`. I do not get any logs in my Nest.js process.

**Comment by julkascript** [comment]
It turns out the problem was that our NestJS was outdated. We upgraded to the latest version (10.1.3) and that was fixed.
