### ISSUE TITLE
Session Storage With Prisma 

### ISSUE THREAD

**Issue by cartersteinhoff** [nestjs-shopify/nestjs-shopify#284]
I am using a package provided by Shopify to set up session storage with Primsa/Postgres. 

https://github.com/Shopify/shopify-app-js/tree/main/packages/shopify-app-session-storage-prisma

I'd like to identify if this will work as intended or if there is additional configuration I'd need to do. I'm getting a "no session found" error when I try and install the App in a store. 

Here is a link to my repo - 
https://github.com/cartersteinhoff/nest-shopify

```ts
import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { AppController } from './app.controller';
import { AppService } from './app.service';

import '@shopify/shopify-api/adapters/node';
import { ApiVersion } from '@shopify/shopify-api';

import { ShopifyCoreModule } from '@nestjs-shopify/core';
import { ShopifyAuthModule } from '@nestjs-shopify/auth';
import { ShopifyGraphqlProxyModule } from '@nestjs-shopify/graphql';

import { PrismaSessionStorage } from '@shopify/shopify-app-session-storage-prisma';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const storage = new PrismaSessionStorage(prisma);

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    ShopifyCoreModule.forRootAsync({
      useFactory: async (configService: ConfigService) => {
        return {
          hostName: configService.get('HOST'),
          apiKey: configService.get('SHOPIFY_API_KEY'),
          apiSecretKey: configService.get('SHOPIFY_API_SECRET'),
          apiVersion: ApiVersion.July23,
          scopes: ['read_products', 'write_products'],
          sessionStorage: storage,
          isEmbeddedApp: false,
          debug: true,
        };
      },
      inject: [ConfigService],
    }),
    ShopifyAuthModule.forRootOnline({
      basePath: 'user',
      returnHeaders: true,
    }),
    ShopifyGraphqlProxyModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

**Comment by tolgap** [comment]
@cartersteinhoff thanks for the detailed report! There's just one thing missing for me 🙂 . Could you paste the full Error and its stacktrace here?

**Comment by cartersteinhoff** [comment]
Certainly. Not much of a trace but here is the error - 
<img width="1227" alt="Screenshot 2023-09-05 at 9 00 23 AM" src="https://github.com/nestjs-shopify/nestjs-shopify/assets/18127153/791e0f3a-cbc9-476d-94c9-5740a0fabdfd">

**Comment by cartersteinhoff** [comment]
I got this working. Reinstalling the app to the store seemed to fix the issue.

**Comment by tolgap** [comment]
@cartersteinhoff I was trying to get the example repo to work but I never worked with Prisma before so was struggling with it... 😅 

Good to see it worked after reinstalling the app!
