### ISSUE TITLE
Upgrade version of shopify-api package

### ISSUE THREAD

**Issue by Ivanshamir** [nestjs-shopify/nestjs-shopify#316]
Hello @tolgap, it seems that `@shopify/shopify-api` package's current version in `8.0.2` but in this awesome repo the version is `"@shopify/shopify-api": "7.7.0",`. So when can we get the latest update? Any idea? Thank you !!

**Comment by tolgap** [comment]
See #310. Upgrade to the latest version of all packages to use v8!
