### ISSUE TITLE
support for token exchange

### ISSUE THREAD

**Issue by schiller-manuel** [nestjs-shopify/nestjs-shopify#411]
I would like to implement token exchange as described here: https://shopify.dev/docs/apps/auth/get-access-tokens/token-exchange

@tolgap do you have recommendations how nestjs-shopify should be structured for this feature?

e.g. we could either

- add a new package `@nestjs-shopify/token-exchange-auth` (or a better name :D)
- add a new decorator `@UseShopifyTokenExchangeAuth` to `@nestjs-shopify/auth`
- make decorator `@UseShopifyAuth` configurable so that it supports token exchange as an option in addition to access mode
- make`ShopifyAuthModule` somehow configurable so it either uses authorization code grant or token exchange.

I currently lean towards the last option but I don't know how such a config option should look like.

**Comment by tolgap** [comment]
Hi @schiller-manuel thank you for opening this!

I just read through the token exchange docs. Shouldn't we always use token exchange if the app is embedded? I would lean towards that side.
