### ISSUE TITLE
Get work, how about examples or guides?

### ISSUE THREAD

**Issue by cnscorpions** [nestjs-shopify/nestjs-shopify#6]
Very excellent project, I'd like to develop Shopify apps via powerful Nest.js too. Is there any guide on handling auth, custom storage, webhook .etc? Thanks in advance

**Comment by tolgap** [comment]
You can check out https://github.com/nestjs-shopify/example-nx-app for an example NestJS/NextJS/MikroORM app.

It uses auth, webhooks, custom storage. The sessions are stored in the database.
