### ISSUE TITLE
Cant resolve dependencies Error

### ISSUE THREAD

**Issue by zifahm** [nestjs-shopify/nestjs-shopify#69]
Im trying to add the webhook module
Tried a lot of things, even tried following the examples app

```
Error: Nest can't resolve dependencies of the ShopifyHmacGuard (?, SHOPIFY_API_CONTEXT). Please make sure that the argument Reflector at index [0] is available in the ShopifyWebhooksModule context.

Potential solutions:
- Is ShopifyWebhooksModule a valid NestJS module?
- If Reflector is a provider, is it part of the current ShopifyWebhooksModule?
- If Reflector is exported from a separate @Module, is that module imported within ShopifyWebhooksModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })
```

Not sure what Reflector means here tho

**Comment by tolgap** [comment]
@zifahm do you happen to have multiple versions of `@nestjs/common` in your project?

Please check thoroughly in your node modules. You might be in a monorepo structure, where you have multiple package-locks, causing clashes in NestJS metadata output.

**Comment by zifahm** [comment]
https://github.com/nestjs/nest/issues/7583#issuecomment-881113577


I guess this might be it? a lib that i might be using is not saying `nest/common` should be a peer dependecy?



But I would see the other version of nest in the lock file tho, I only see just 1 version.

**Comment by zifahm** [comment]
Okay I fixed it

I had to no hoist this package as well

`**/nestjs-shopify
**/nestjs-shopify/**`

**Comment by tolgap** [comment]
@zifahm not sure what that means, but good to see you worked it out 🙂 .

Mind explaining it in detail in this issue, if any others ran into this? 👀

**Comment by zifahm** [comment]
sure!

Yarn hoists all of its packages to the main node_modules if your uising yarn wrokpaces

you can stop the hoisintg per package by saying "nohoist" in your package.json, so now the packages that was passed in would not get hoisted.

They wrote an indepth blog about it too
https://classic.yarnpkg.com/blog/2018/02/15/nohoist/

I had already done a `nohoist` for the  nestjs packages

now I had to add nestjs-shopify package too the list too

```
  "workspaces": {
    "nohoist": [
      "**/@nestjs",
      "**/@nestjs/**",
      "**/@nestjs-shopify",
      "**/@nestjs-shopify/**",
    ]
  }
  ```
