### ISSUE TITLE
Webhook handler not getting processed?

### ISSUE THREAD

**Issue by zifahm** [nestjs-shopify/nestjs-shopify#72]
Webhook handler is not getting processed?

Not sure whats happening here. I do get a sucessfull webhook registration.

After a webbhok gets fired, I dont see it getting processed. 

Followed everthing to the teeth, I have even set `rawBody` in main.

could this be the problem?

https://github.com/Shopify/shopify-api-js/blob/87399c49fa98d7fbd7a9881f1dc76426d061dd1c/docs/usage/webhooks.md#:~:text=To%20use%20Express,webhooks.process()%20expects%3A

**Comment by zifahm** [comment]
Okay fixed!

setting rawBody in the  in the nestFactory.create function doenst seem to do anything. Not sure why!

had to do it mannually uisng app.use

```javascript
  app.use((request: Request, res: Response, next: NextFunction) => {
   if (request.path.indexOf('/store/shopify/webhooks') === 0) {
      express.json({
        verify: (req: Request, _, buf) => {
          req['rawBody'] = buf;
        },
      })(request, res, next);
    } else {
      express.json()(request, res, next);
    }
  });

```

**Comment by tolgap** [comment]
@zifahm can you show your `main.ts` file? I've been running this on my own projects, and I receive the webhooks correctly with `rawBody: true`.

**Comment by zifahm** [comment]
@tolgap sure!

```javascript

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule, {
    bodyParser: false,
    cors: {
      credentials: true,
      origin: corsOrigin,
    },
  });

  if (NODE_ENV === 'production') {
    app.set('trust proxy', 1);
  }


  if (NODE_ENV === 'development') {
    const serverAdapter = new ExpressAdapter();
    serverAdapter.setBasePath('/bull-board');

    const aQueue = app.get<Queue>(`BullQueue_${STORE_PRODUCT_UPLOAD_QUEUE}`);
    const bQueue = app.get<Queue>(`BullQueue_${USER_CUSTOMER_UPLOAD_QUEUE}`);
    const cQueue = app.get<Queue>(
      `BullQueue_${STORE_SEND_EMAIL_TO_SUBSCRIBER_LIST_QUEUE}`,
    );
    const dQueue = app.get<Queue>(`BullQueue_${STORE_WORKFLOW_QUEUE}`);

    createBullBoard({
      queues: [
        new BullAdapter(aQueue),
        new BullAdapter(bQueue),
        new BullAdapter(cQueue),
        new BullAdapter(dQueue),
      ],
      serverAdapter,
    });

    app.use('/bull-board', serverAdapter.getRouter());
  }

  app.use((request: Request, res: Response, next: NextFunction) => {
    if (
      request.path.indexOf('/store/stripe-webhook') === 0 ||
      request.path.indexOf('/store/shopify/webhooks') === 0
    ) {
      json({
        verify: (req: RawBodyRequest<Request>, _, buf) => {
          req.rawBody = buf;
        },
      })(request, res, next);
    } else {
      json()(request, res, next);
    }
  });

  app.use(
    session({
      store: new RedisStore({
        client: new Redis(REDIS_URL, {
          family: 6,
        }),
      }),
      name: process.env.COOKIE_NAME,
      secret: process.env.SESSION_SECRET,
      resave: false,
      saveUninitialized: false,
      cookie: {
        maxAge: 1000 * 60 * 60 * 24 * 365 * 7,
        httpOnly: true,
        domain:
          NODE_ENV === 'production'
            ? process.env.FRONTEND_HOST
            : 'localhost.com',
        secure: NODE_ENV === 'production' ? true : false,
      },
    }),
  );

  await app.listen(PORT);
  console.log(`Server started at http://localhost:${PORT}/graphql`);
  const server = app.getHttpServer();
  const router = server._events.request._router;

  if (process.env.NODE_ENV === 'development') {
    const availableRoutes: [] = router.stack
      .map((layer: any) => {
        if (layer.route) {
          return {
            route: {
              path: layer.route?.path,
              method: layer.route?.stack[0].method,
            },
          };
        }
        return undefined;
      })
      .filter((item: any) => item !== undefined);
    console.log(availableRoutes);
  }
}
bootstrap();
```

**Comment by tolgap** [comment]
@zifahm you need to do this in order to have `rawBody` work:

```diff
const app = await NestFactory.create<NestExpressApplication>(AppModule, {
- bodyParser: false,
+ rawBody: true,
  cors: {
    credentials: true,
    origin: corsOrigin,
  },
});
```

```diff
-  app.use((request: Request, res: Response, next: NextFunction) => {
-    if (
-      request.path.indexOf('/store/stripe-webhook') === 0 ||
-      request.path.indexOf('/store/shopify/webhooks') === 0
-    ) {
-      json({
-        verify: (req: RawBodyRequest<Request>, _, buf) => {
-          req.rawBody = buf;
-        },
-      })(request, res, next);
-    } else {
-      json()(request, res, next);
-    }
-  });
```

**Comment by zifahm** [comment]
@tolgap  Yeah I know, but it doesnt work, it never did.

Also I read somewhere having rawBody conversions like that eats up the ram. 

Unable to find source. I'll find it in a while.

**Comment by tolgap** [comment]
> Yeah I know, but it doesnt work, it never did.

I've used this feature since it was introduced. So whatever you're doing to use it, saying "it doesn't work" will not make it work 🙂 .

> Also I read somewhere having rawBody globally like that eats up the ram.

Besides assigning a `body`, it also assigns a `rawBody` to the request. It's exactly what the `body-parser` itself does by default.

If you're concerned about RAM, we're talking about Stripe and Shopify webhooks here. They will be at most 500Kb of strings. I doubt these kinds of webhooks will ever get you in trouble with RAM and assigning the raw body to the request.
You would reach the max connection limit of your networking layer, before reaching RAM limitations.

**Comment by zifahm** [comment]
> I've used this feature since it was introduced. So whatever you're doing to use it, saying "it doesn't work" will not make it work slightly_smiling_face .

I guess im doing something wrong somewhere, i'm unable to find why rawbody is not working after setting it to true, I just had to do this, so I could continue working, rather than get boggled down.

>f you're concerned about RAM, we're talking about Stripe and Shopify webhooks here. They will be at most 500Kb of strings. I doubt these kinds of webhooks will ever get you in trouble with RAM and assigning the raw body to the request.
You would reach the max connection limit of your networking layer, before reaching RAM limitations.

No I meant adding rawbody globally like for every request that comes in. Might have been max connection limit I have read about, maybe it's not ram. I just remeber reading "don't do rawbody globally".
