### ISSUE TITLE
Cant get req 

### ISSUE THREAD

**Issue by anhquanduong2007** [nestjs-shopify/nestjs-shopify#80]
Hi, i am trying to log out req but got this error and here my code:

![image](https://user-images.githubusercontent.com/81066373/208610047-564f476e-33d3-4607-b67f-a33fe405e9b7.png)
![image](https://user-images.githubusercontent.com/81066373/208610310-7de43b2f-8e1d-46f0-a8cc-94a4af9a441b.png)

**Comment by tolgap** [comment]
@anhquanduong2007 what versions of `@nestjs-shopify/*` are you using?

**Comment by anhquanduong2007** [comment]
Hi, I am using version 0.0.15 for @nestjs-shopify/* and version 9.0.4 for @nestjs/*

**Comment by tolgap** [comment]
@anhquanduong2007 did you consider upgrading to `@nestjs-shopify/*: 2.0.0`?

**Comment by tolgap** [comment]
@anhquanduong2007 also, could you perhaps show the repo, or create a reproduction on [codesandbox](codesandbox.io/) or [stackblitz](https://stackblitz.com/)?

**Comment by tolgap** [comment]
@anhquanduong2007 Tried to replicate it on stackblitz: https://stackblitz.com/edit/nestjs-typescript-starter-dyquiq?file=src/app.module.ts

I used v2 of `@nestjs-shopify/webhooks`. It seems to just work. Could you try forking that and maybe showing what breaks it?

**Comment by anhquanduong2007** [comment]
Hi, i think i found the bug for this problem, probably due to nestjs version conflict, thanks for your help!
