### ISSUE TITLE
Move jsonwebtoken from dev dep to dependency

### ISSUE THREAD

**Issue by zifahm** [nestjs-shopify/nestjs-shopify#82]
jsonwebtoken is used here:

https://github.com/nestjs-shopify/nestjs-shopify/blob/8bbff278a4a7d51583d2a65541de7c1178928e8a/packages/auth/src/utils/decode-session-token.util.ts#L2

Need to move it as a dependency as it crashes in prod

https://github.com/nestjs-shopify/nestjs-shopify/blob/ffcc15c17257a3fcc77d10dbc5d8edf5f113861b/package.json#L43

**Comment by zifahm** [comment]
Thanks, I would have done it but, Its way easier for you.

**Comment by tolgap** [comment]
@zifahm thanks for reporting! I had the dependency in all my projects already... so forgot to include it in the actual package itself 🤡 

Released `@nestjs-shopfy/auth: 2.0.1` with the dependency included. 🎉

**Comment by zifahm** [comment]
yeah!, I just saw jsonwebtoken got updated to version 9, so had to make this permanent here, so I could delete the one I installed
